### PR TITLE
Issue#47

### PR DESCRIPTION
**Pull request by TomazMartins**
Solving the issue #47.

### CODE REVIEW

**Comment by rafamanzo** [comment]
Nice @TomazMartins !

The tests result look good. That's the way to go :trophy: 

Just a few questions:

* You have correctly moved the features from processing to repository
  * What do you think about putting them inside a `processing` subfolder then
* There are some features which names end with `of`. This made sense when they were from processing. Don't you think better renaming them removing those suffixes?
  * Beyond, this is something that should get changed in the step definitions as well if you agree

After this I think we are ready for a merge. After the merge we are still going to remove the MetricResult's deprecated method (if you want, feel free to fix this as well, you 'll be very welcomed!) and then finally a release that should be `v0.3.0`.

Thanks again for the great job!

**Comment by TomazMartins** [comment]
Thank you!

About the questions:
**What do you think about putting them inside a `processing` subfolder then?**
Do you mean create a subfolder inside `processing` only to putting this features? I understood. To keep organization, right? Ok! I will do it!

**Don't you think better renaming them removing those suffixes?**
I agree! I will do it!

**After the merge we are still going to remove the MetricResult's deprecated method.**

I can do this. 
=]

**Comment by rafamanzo** [comment]
Yes, you've understood correctly about the `processing` subfolder inside the `repositories` one. Thanks :)

**Comment by rafamanzo** [comment]
Hi @TomazMartins how is this going?

**Comment by TomazMartins** [comment]
Hi, @rafamanzo!
Sorry for the delay.

I just sent what was requested.
=]

**Comment by rafamanzo** [comment]
Thanks a lot, just did a last review and noticed that you've commented out instead of deleting the code. Is there a special reason? If not you can go for it and we merge it!

**Comment by TomazMartins** [comment]
Ops...
I forgot it. There are no special reason. I only forgot to delete it.
My apologies for this.

I think now it is ok.

**Comment by rafamanzo** [comment]
One more thing that I just noticed now and already fixed. See: https://github.com/mezuro/kalibro_client/pull/54

The private method `repository` is no longer necessary. But, don't worry I've already fixed it.

**Comment by TomazMartins** [comment]
Thanks!

**Pull request merged**
