### PR TITLE
Removed unnecessary methods.

### PR DESCRIPTION
**Pull request by diegoamc**
Signed off by: Daniel Alves <danpaulalves@gmail.com>

### CODE REVIEW

**Comment by rafamanzo** [comment]
How are the `INF`and `-INF` handled now?

**Comment by diegoamc** [comment]
They are not handled. We need to implement that on Kalibro Configurations.

**Comment by rafamanzo** [comment]
They were causing problems?

Em Fri Feb 06 2015 at 18:14:21, Diego de Araújo Martinez Camarinha <
notifications@github.com> escreveu:

**Comment by diegoamc** [comment]
Yes, because INF and -INF sent them as strings to Kalibro Configurations, we always got "Begginning/end must be numeric".

We could try and solve this by sending the constants FLOAT::INFINITY or -FLOAT::INFINITY, but I think JSON can't handle those values.

**Comment by rafamanzo** [comment]
You're right JSON can't represent INF, that's why we firt represented it as
string I think. Apparently Prezento's old validation already handled the
string case:
https://github.com/mezuro/prezento/blob/master/app/models/validators/greater_than_beginning_validator.rb

Em Fri Feb 06 2015 at 18:22:42, Diego de Araújo Martinez Camarinha <
notifications@github.com> escreveu:

**Pull request merged**
