### PR TITLE
Added range method to kalibro range

### PR DESCRIPTION
**Pull request by marcheing**
It creates a range suitable for checking values for a kalibro range

Signed off by: Daniel Miranda <danielkza2@gmail.com>

### CODE REVIEW

**Comment by diegoamc** [comment]
Can't you guys explain better the motivation for this PR?

Where will it be used? Why the previous way was not suitable?

**Comment by danielkza** [comment]
We created it to unify how kalibro_processor and prezento do the range checks. Each had their own implementation, that handled the 'INF' values manually, so we moved it to kalibro_client.

**Comment by rafamanzo** [comment]
What do you think about individually testing `lib/kalibro_client/helpers/range_methods.rb`?

**Comment by danielkza** [comment]
Seems better indeed, we hadn't actually split the methods into a module earlier, but then forgot to change the tests accordingly.

**Pull request merged**
